(function() {var implementors = {};
implementors["agilulf_driver"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_driver/struct.AgilulfClient.html\" title=\"struct agilulf_driver::AgilulfClient\">AgilulfClient</a>",synthetic:false,types:["agilulf_driver::client::AgilulfClient"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_driver/struct.MultiAgilulfClient.html\" title=\"struct agilulf_driver::MultiAgilulfClient\">MultiAgilulfClient</a>",synthetic:false,types:["agilulf_driver::client::MultiAgilulfClient"]},];
implementors["agilulf_protocol"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_protocol/request/struct.PutCommand.html\" title=\"struct agilulf_protocol::request::PutCommand\">PutCommand</a>",synthetic:false,types:["agilulf_protocol::request::PutCommand"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_protocol/request/struct.GetCommand.html\" title=\"struct agilulf_protocol::request::GetCommand\">GetCommand</a>",synthetic:false,types:["agilulf_protocol::request::GetCommand"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_protocol/request/struct.ScanCommand.html\" title=\"struct agilulf_protocol::request::ScanCommand\">ScanCommand</a>",synthetic:false,types:["agilulf_protocol::request::ScanCommand"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_protocol/request/struct.DeleteCommand.html\" title=\"struct agilulf_protocol::request::DeleteCommand\">DeleteCommand</a>",synthetic:false,types:["agilulf_protocol::request::DeleteCommand"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"agilulf_protocol/request/enum.Command.html\" title=\"enum agilulf_protocol::request::Command\">Command</a>",synthetic:false,types:["agilulf_protocol::request::Command"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"agilulf_protocol/struct.Slice.html\" title=\"struct agilulf_protocol::Slice\">Slice</a>",synthetic:false,types:["agilulf_protocol::slice::Slice"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
